### ISSUE TITLE
Error in ./~/react-shopping-cart/dist/components/Product/Product.js

### ISSUE THREAD

**Issue by tarangdave** [olegnn/react-shopping-cart#1]
Help me solve this error

> Error in ./~/react-shopping-cart/dist/components/Product/Product.js
Module not found: 'react-scroll/lib/mixins/animate-scroll' in C:\Users\Tarang\Documents\GitHub\community-platform\node_modules\react-shopping-cart\dist\components\Product

**Comment by olegnn** [comment]
Because in the newest version of react-scroll package library paths changed, absolute imports, used in Product module, are corrupted. Now I'm working on the new version of package, which will bring a lot of fixes and updates, so, you could just use react-scroll@1.2.0 for now or wait for coming update.
