### ISSUE TITLE
get error

### ISSUE THREAD

**Issue by jthink0228** [olegnn/react-shopping-cart#2]
hi
i try to use react-shopping-cart in my project

i am follow the step to do,
get the error message:

```
Failed to compile

./~/react-shopping-cart/src/index.js
Module parse failed: E:\jcart\node_modules\react-shopping-cart\src\index.js Unexpected token (8:9)
You may need an appropriate loader to handle this file type.
| export { default as CheckoutButtonComponent } from './components/CheckoutButton/CheckoutButton';
| export { default as cartReducer } from './reducers/cart';
| export * as cartActions from './actions';
| export * as actionTypes from './actionTypes';
| export * as cartSelectors from './selectors';

This error occurred during the build time and cannot be dismissed.
```

here is my package.json:

{
  "name": "jcart",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "react-scripts": "1.0.7"
  },
  "dependencies": {
    "react": "^15.5.4",
    "react-dom": "^15.5.4",
    "react-shopping-cart": "^1.5.8"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}

**Comment by olegnn** [comment]
Hey!
How do you import parts of react-shopping-cart package? Using
`import { Cart } from 'react-shopping-cart';` 
or somehow else? Because it looks like you are trying to import source es6+ files, not transpiled to es5. 
If you've done all according to instructions, check the latest (1.5.9) version, hope it will work correct.
